### ISSUE TITLE
the init function doesn't start serveHttp

### ISSUE THREAD

**Issue by soapdog** [ssbc/ssb-viewer#3]
# Desired outcome
Add and enable `ssb-viewer` plugin. Access a `http://example.com:8807/<msg id>` URL and see the content.

# What really happens
Nothing because `init()` doesn't call `serveHttp()` so simply adding and enabling the plugin is not enough to start the viewer.

# How to fix
Just call `serveHttp()` from `init()`

### Remarks
This is what we did for our pub-severs for ticktack project. We have two of them where I added this little line to `init()` by hand. Do you want  a PR for that?

**Comment by arj03** [comment]
Ohh, are you talking about the calm branch? I think that is a bug. I merged in the non-controversal changes from that branch (rendering blogs).

**Comment by soapdog** [comment]
@arj03 yes, I was talking about the `calm` branch. I had the impression that the blog routines were only present there because I remember them not working on master couple weeks ago. Was this merge recent?

**Comment by arj03** [comment]
Yeah I moved everything into master. calm is dead
