### ISSUE TITLE
Render gatherings correctly

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-viewer#6]
I think this is a really important feature to introduce new people to ssb. I often create fb events and like to create a parallel gathering in ssb, but as it is now I don't have much of a way to link people to the gathering from the event, just the other way around.

I'm considering doing this as my first contribution to ssb code. Would I be getting in way over my head? Pointers would be appreciated either way :sweat_smile:

**Comment by arj03** [comment]
Hey @Powersource. The ssb-viewer code is quite straightforward so this is a perfect place to contribute. Take a look at render.js to see how other messages are rendered. Gatherings are mostly a message of type gathering and then a bunch of abouts adding information. You should be able to get the abouts using backlinks index.
