### ISSUE TITLE
should be opt-in

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-viewer#8]
Numerous people were confused up to shocked that these viewers exists and find opt-out upsetting.

The logic [here](https://github.com/ssbc/ssb-viewer/blob/78e7e8a0087325795a746c98fad5255a3ae405aa/lib/about.js#L34) would just have to be turned on it's head. As in: no `publichWebHosting:true` message means don't display that feed.

**Comment by edwardgalligan** [comment]
I can't imagine many people would ever opt-in if this logic was turned around as proposed, making the viewers largely useless.

If it's truly an issue of trust, even with this being opt-in any malicious pub would be free to ignore the message flag and publish anyway as long as the messages are being transmitted to it, so the opt-in gives people a false sense of security. I find the assumption that messages transmitted to pubs would be thought of as being private or even reduced-exposure to be a deeply troubling assumption to encourage/entertain.

**Comment by cryptix** [comment]
Thanks @edwardgalligan - I raised similar concerns on the ssb thread but it felt wrong to link it here.

**Comment by cryptix** [comment]
This already happend and is thus solved.
